### ISSUE TITLE
Note: count vs. nunique differences

### ISSUE THREAD

**Issue by Caealana** [MinderbinderMJ/Capstone2-Intro-to-Data-Analysis#1]
count will count all scientific names that show up for each category of endangerment. However, some of the scientific names are repeated in the data, so you should use nunique so that you only count the unique species for each category.
Refer to the following picture to see how the results from using count and nunique differ:

<img width="845" alt="screenshot at apr 29 14-48-01" src="https://user-images.githubusercontent.com/14001120/39409379-5b8fb504-4bbc-11e8-80dc-47c7425d7c37.png">

**Comment by MinderbinderMJ** [comment]
Great feedback.  That makes sense.  I'll look into it.
