### ISSUE TITLE
Great job: contingency tables

### ISSUE THREAD

**Issue by Caealana** [MinderbinderMJ/Capstone2-Intro-to-Data-Analysis#2]
```
contingency2 = [[30, 146], [5, 73]]
chi2_contingency(contingency2)
```

Your contingency tables were both correct, demonstrating your mastery over the statistical concepts taught in this course. Nice job!

I would suggest you consider being more specific with your variable names. For example, the contingency table names can refer to the two groups being compared. This will help in easily remembering and choosing the variables you want to use.

**Comment by MinderbinderMJ** [comment]
Good point.  From the course I got used to using the refs like that.  Just seemed simpler as I steamed through the project.
