### ISSUE TITLE
Great job: efficient lambdas

### ISSUE THREAD

**Issue by Caealana** [MinderbinderMJ/Capstone2-Intro-to-Data-Analysis#3]
```
species['is_sheep'] = species.common_names.apply(lambda x: 'Sheep' in x)
species.head()


# Select the rows of `species` where `is_sheep` is `True` and examine the results.

# In[106]:


species[species.is_sheep]
```

Your lambdas are written well! They work correctly towards accomplishing the goal, and they are efficient with no unnecessary steps.

**Comment by MinderbinderMJ** [comment]
Great!  Thanks again for the feedback.  Yeah, lambdas proved a little confusing at first, but as I got the hang of them they really helped.
